### ISSUE TITLE
Need some presentation of imaginary functionality  and what has been done till now

### ISSUE THREAD

**Issue by gkorepanov** [dmylnikov/intel-iot#6]
Who will take this? Probably @Tismoney?

**Comment by Tismoney** [comment]
I don't use Windows more. So, I can't make amazing presentation. @gkorepanov May be  will you try?

**Comment by Tismoney** [comment]
Or @DonVladon do you want?

**Comment by gkorepanov** [comment]
I'm on GSoC for now, so can't take it up.

**Comment by Tismoney** [comment]
I am busy now too.

**Comment by gkorepanov** [comment]
Well, at least we should have good description of everything on our README page. It's a request of our colleagues doing the interface stuff

**Comment by gkorepanov** [comment]
I've done it. Closing.
